/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : string,
  'customerName' : string,
  'status' : string,
  'total' : bigint,
  'customerPhone' : string,
  'createdAt' : bigint,
  'upiTxnRef' : string,
  'customerAddress' : string,
  'items' : Array<OrderItem>,
}
export interface OrderInput {
  'customerName' : string,
  'total' : bigint,
  'customerPhone' : string,
  'upiTxnRef' : string,
  'customerAddress' : string,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'qty' : bigint,
  'productId' : string,
  'productName' : string,
  'price' : bigint,
}
export interface Product {
  'id' : string,
  'active' : boolean,
  'imageHash' : string,
  'name' : string,
  'description' : string,
  'imageEmoji' : string,
  'stock' : bigint,
  'category' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<[OrderInput], string>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[string], Array<Order>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[string], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updateProduct' : ActorMethod<[string, Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];